# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35b36f06aabf5a0a12c5524fbc5e0c0377d191bd1d1f067d2211a8623bf56f868b52cd640951af78d44339a5bbca35561715344f8f0db48deb62d48427ddf867

test:
  secret_key_base: c438de19f2faf6041f08ec7f7dfa00726ef245fdb46deec39a01dd24ee3bf9139e1db92556a7e878fb075c2fec4c2c26f017817b1dded6d44f55023abdb9ad82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
